// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs-fRBtU28plcIHSXTderVfCM3Fnw7omA',
    appId: '1:484051238600:web:b287f5ee433ece646ceffd',
    messagingSenderId: '484051238600',
    projectId: 'appchef12',
    authDomain: 'appchef12.firebaseapp.com',
    storageBucket: 'appchef12.appspot.com',
    measurementId: 'G-VKKF4VMRSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEh1zJSjvAbf2RN_xPba-__EI0uuQu3jE',
    appId: '1:484051238600:android:e7f32ca492628f1d6ceffd',
    messagingSenderId: '484051238600',
    projectId: 'appchef12',
    storageBucket: 'appchef12.appspot.com',
  );

}